# 02- Construção das tabelas dimensões
---
## Objetivo

Este notebook tem como objetivo construir as tabelas dimensão utilizadas no modelo dimensional do projeto de Business Intelligence sobre assistência estudantil da UFPB.

As dimensões são obtidas a partir das consultas realizadas no SEDAP+ e passam por etapas de verificação, tratamento e padronização antes de serem utilizadas na construção da tabela fato e do dashboard.

 ---

## Importação das bibliotecas necessárias

In [1]:
import pandas as pd

 ---
# 1. Construção da Dimensão Curso
## 1.1 Carregar os dados

In [7]:
dim_curso = pd.read_csv(r"C:\Users\reisc\Desktop\Projeto-Analise-de-Dados-main\data\raw\SEDAP\alunos_por_curso.csv")

## 1.2 Conhecendo a base

In [8]:
dim_curso.head()

,CO_CURSO,NO_CURSO,CO_CINE_ROTULO,TP_GRAU_ACADEMICO,TP_MODALIDADE_ENSINO,TOTAL_ALUNOS
0,13397,CIÊNCIAS CONTÁBEIS,0411C01,1,1,1438
1,13418,PEDAGOGIA,0113P01,2,1,1382
2,13398,DIREITO,0421D01,1,1,1137
3,13424,MEDICINA,0912M01,1,1,844
4,107548,LETRAS - LÍNGUA PORTU,0115L13,2,1,766

In [9]:
dim_curso.info()

<class 'pandas.DataFrame'>
RangeIndex: 119 entries, 0 to 118
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   CO_CURSO              119 non-null    int64
 1   NO_CURSO              119 non-null    str
 2   CO_CINE_ROTULO        119 non-null    str
 3   TP_GRAU_ACADEMICO     119 non-null    int64
 4   TP_MODALIDADE_ENSINO  119 non-null    int64
 5   TOTAL_ALUNOS          119 non-null    int64
dtypes: int64(4), str(2)
memory usage: 5.7 KB

In [10]:
dim_curso.describe(include="all")

,CO_CURSO,NO_CURSO,CO_CINE_ROTULO,TP_GRAU_ACADEMICO,TP_MODALIDADE_ENSINO,TOTAL_ALUNOS
count,1.190000e+02,119,119,119.000000,119.000000,119.000000
unique,NaN,85,97,NaN,NaN,NaN
top,NaN,CIÊNCIAS BIOLÓGICAS,0113P01,NaN,NaN,NaN
freq,NaN,5,4,NaN,NaN,NaN
mean,4.991313e+05,NaN,NaN,1.352941,1.084034,334.151261
std,8.827670e+05,NaN,NaN,0.514011,0.278611,236.972702
min,1.339400e+04,NaN,NaN,1.000000,1.000000,7.000000
25%,1.345600e+04,NaN,NaN,1.000000,1.000000,164.000000
50%,1.099500e+05,NaN,NaN,1.000000,1.000000,279.000000
75%,1.124486e+06,NaN,NaN,2.000000,1.000000,452.500000
max,5.001240e+06,NaN,NaN,3.000000,2.000000,1438.000000

## 1.3 Verificando valores ausentes

In [6]:
dim_curso.isna().sum()

CO_CURSO                0
NO_CURSO                0
CO_CINE_ROTULO          0
TP_GRAU_ACADEMICO       0
TP_MODALIDADE_ENSINO    0
TOTAL_ALUNOS            0
dtype: int64

## 1.4 Traduzindo códigos

In [11]:
grau = {
    1: "Bacharelado",
    2: "Licenciatura",
    3: "Tecnológico"
}

modalidade = {
    1: "Presencial",
    2: "EaD"
}

dim_curso["TP_GRAU_ACADEMICO"] = dim_curso["TP_GRAU_ACADEMICO"].map(grau)

dim_curso["TP_MODALIDADE_ENSINO"] = dim_curso["TP_MODALIDADE_ENSINO"].map(modalidade)

In [ ]:
# Conferindo se as alterações foram aplicadas corretamente
dim_curso.head()

,CO_CURSO,NO_CURSO,CO_CINE_ROTULO,TP_GRAU_ACADEMICO,TP_MODALIDADE_ENSINO,TOTAL_ALUNOS
0,13397,CIÊNCIAS CONTÁBEIS,0411C01,Bacharelado,Presencial,1438
1,13418,PEDAGOGIA,0113P01,Licenciatura,Presencial,1382
2,13398,DIREITO,0421D01,Bacharelado,Presencial,1137
3,13424,MEDICINA,0912M01,Bacharelado,Presencial,844
4,107548,LETRAS - LÍNGUA PORTU,0115L13,Licenciatura,Presencial,766

In [13]:
# Conferindo duplicidades
dim_curso.duplicated().sum()

np.int64(0)

In [14]:
dim_curso["CO_CURSO"].duplicated().sum()

np.int64(0)

In [15]:
# Informações gerais
print(f"Número de cursos: {len(dim_curso)}")
print(f"Modalidades: {dim_curso['TP_MODALIDADE_ENSINO'].unique()}")
print(f"Graus acadêmicos: {dim_curso['TP_GRAU_ACADEMICO'].unique()}")

Número de cursos: 119
Modalidades: <StringArray>
['Presencial', 'EaD']
Length: 2, dtype: str
Graus acadêmicos: <StringArray>
['Bacharelado', 'Licenciatura', 'Tecnológico']
Length: 3, dtype: str

## 1.5 Exportando a dimensão

In [18]:
dim_curso.to_csv(
    r"C:\Users\reisc\Desktop\Projeto-Analise-de-Dados-main\data\processed\Dimensões\dim_curso.csv",
    index=False,
    encoding="utf-8-sig"
)

# 2. Construção da Dimensão